<<<<<<< Updated upstream
CRITICAL - 2022-03-28 01:51:47 --> Invalid file: pet_view/person_main.php
#0 C:\xampp\htdocs\petforyou\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pet_view/person...')
#1 C:\xampp\htdocs\petforyou\system\View\View.php(424): CodeIgniter\View\View->render('pet_view/person...', NULL, true)
#2 C:\xampp\htdocs\petforyou\app\Views\member_view\person.php(9): CodeIgniter\View\View->include('pet_view/person...')
#3 C:\xampp\htdocs\petforyou\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\petforyou\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\petforyou\system\Common.php(1089): CodeIgniter\View\View->render('member_view/per...', Array, true)
#6 C:\xampp\htdocs\petforyou\app\Controllers\View.php(47): view('member_view/per...', Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\View->person_view()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\View))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
=======
CRITICAL - 2022-03-28 09:04:00 --> The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\petforyou\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 C:\xampp\htdocs\petforyou\public\index.php(28): require('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-03-28 02:28:12 --> Class 'MemberModel' not found
#0 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#1 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-03-28 02:49:48 --> Class 'MemberModel' not found
#0 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#1 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2022-03-28 02:51:38 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:39 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:39 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:39 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:40 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:40 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:40 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:40 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:54 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:51:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:51:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:53:35 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:53:35 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:53:36 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:53:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:53:36 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:53:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:53:36 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:53:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:53:37 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:53:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:53:37 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:53:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:53:37 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:53:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(21): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:54:52 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:54:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:54:53 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:54:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:54:53 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:54:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:54:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:54:54 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:54:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:54:54 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:57:23 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:57:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:57:24 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:57:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:57:24 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:57:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:57:25 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:57:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:57:25 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:57:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:57:26 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-03-28 02:57:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\petforyou\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\petforyou\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\petforyou\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\petforyou\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#4 C:\xampp\htdocs\petforyou\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#5 C:\xampp\htdocs\petforyou\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(20): CodeIgniter\BaseModel->save(Array)
#7 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-03-28 02:57:44 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 02:59:14 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 02:59:17 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 02:59:18 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 02:59:18 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 02:59:18 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 02:59:19 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:04:23 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:05 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:06 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:06 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:07 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:11 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:12 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:12 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:12 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:13 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:06:13 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:38 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:39 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:39 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:39 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:39 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:40 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:40 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:40 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:40 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:41 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:41 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:41 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:41 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:43 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:43 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:08:43 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:12:14 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:12:35 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:12:36 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:12:36 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:12:36 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:12:36 --> Unknown column 'user_photo' in 'field list'
CRITICAL - 2022-03-28 03:16:18 --> user is not a valid database connection group.
#0 C:\xampp\htdocs\petforyou\system\Common.php(312): CodeIgniter\Database\Config::connect('user', true)
#1 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(12): db_connect('user')
#2 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#3 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-03-28 03:16:48 --> user is not a valid database connection group.
#0 C:\xampp\htdocs\petforyou\system\Common.php(312): CodeIgniter\Database\Config::connect('user', true)
#1 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(12): db_connect('user')
#2 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#3 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-03-28 03:16:48 --> user is not a valid database connection group.
#0 C:\xampp\htdocs\petforyou\system\Common.php(312): CodeIgniter\Database\Config::connect('user', true)
#1 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(12): db_connect('user')
#2 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#3 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-03-28 03:16:49 --> user is not a valid database connection group.
#0 C:\xampp\htdocs\petforyou\system\Common.php(312): CodeIgniter\Database\Config::connect('user', true)
#1 C:\xampp\htdocs\petforyou\app\Controllers\UserController.php(12): db_connect('user')
#2 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#3 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-03-28 03:16:54 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:16:55 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:16:55 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:16:56 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:16:56 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:16:57 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:16:57 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:16:57 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:16:57 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:18:40 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:18:41 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:18:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:18:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:18:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:18:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:20:32 --> Unknown column 'user_photo' in 'field list'
CRITICAL - 2022-03-28 03:20:32 --> Call to a member function errors() on bool
#0 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(832): App\Controllers\UserController->index()
#1 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2022-03-28 03:20:37 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:21:54 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:21:54 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:21:55 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:21:55 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:21:55 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:21:55 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:08 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:09 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:09 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:09 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:09 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:09 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:32 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:34 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:35 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:35 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:35 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:35 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:22:44 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:23:41 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:23:41 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:23:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:23:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:23:42 --> Unknown column 'user_photo' in 'field list'
ERROR - 2022-03-28 03:26:19 --> Unknown column 'user_photo' in 'field list'
CRITICAL - 2022-03-28 03:43:24 --> Class 'user' not found
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
>>>>>>> Stashed changes
CRITICAL - 2022-03-28 10:28:24 --> syntax error, unexpected '<<' (T_SL), expecting end of file
#0 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-03-28 10:28:26 --> syntax error, unexpected '<<' (T_SL), expecting end of file
#0 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-03-28 10:28:28 --> syntax error, unexpected '<<' (T_SL), expecting end of file
#0 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 C:\xampp\htdocs\petforyou\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\petforyou\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
